## JCP Client

#jcp.connect: 'false'                              # JCP_CONNECT_DEF          = "true";
#jcp.client.refresh: '5'                           # JCP_REFRESH_TIME_DEF     = "30";
jcp.url.apis: 'api-stage.johnosproject.org'       # JCP_URL_DEF_APIS         = "apis.johnosproject.org";
jcp.url.auth: 'auth-stage.johnosproject.org'      # JCP_URL_DEF_AUTH         = "auth.johnosproject.org";
jcp.client.id: 'test-client-obj'                  # JCP_CLIENT_ID_DEF        = "";
#jcp.client.secret: ''                             # JCP_CLIENT_SECRET_DEF    = "";
jcp.client.secret: '2d1f9b96-70d3-443b-b21b-08a401ddc16c'   # Stage
#jcp.client.secret: '04526df3-8752-48d2-be2b-7dca8229aa32'   # Production


## JOD Object

#jod.obj.name: 'Banana_99'                         # JODOBJ_NAME_DEF          = "";
#jod.obj.id_cloud: 'XXXXX-XXXXX-XXXXX'             # JODOBJ_IDCLOUD_DEF       = "";
#jod.obj.id_hw: 'XXXXX'                            # JODOBJ_IDHW_DEF          = "";


## Executors

jod.executor_mngr.pullers:                        # JODPULLER_IMPLS_DEF       = ""
  'tstP://com.robypomper.josp.jod.executor.PullerTest
   shell://com.robypomper.josp.jod.executor.PullerUnixShell
   http://com.robypomper.josp.jod.executor.impls.http.PullerHTTP'
jod.executor_mngr.listeners:                      # JODLISTENER_IMPLS_DEF     = ""
  'tstL://com.robypomper.josp.jod.executor.ListenerTest
   tstLAdv://com.robypomper.josp.jod.executor.ListenerTestAdv
   file://com.robypomper.josp.jod.executor.ListenerFiles'
jod.executor_mngr.executors:                      # JODEXECUTOR_IMPLS_DEF     = ""
  'tstE://com.robypomper.josp.jod.executor.ExecutorTest
   shell://com.robypomper.josp.jod.executor.ExecutorUnixShell
   file://com.robypomper.josp.jod.executor.ExecutorFiles
   http://com.robypomper.josp.jod.executor.impls.http.ExecutorHTTP'


## Structure

jod.structure.path: 'configs/struct.jod'                 # JODSTRUCT_PATH_DEF       = "struct.jod";


## Permissions

#jod.permissions.path: 'perms.jod'                 # JODPERM_PATH_DEF         = "perms.jod";
#jod.permissions.refresh: '30'                     # JODPERM_REFRESH_DEF      = "300";
#jod.permissions.generation_strategy: 'standard'   # JODPERM_GENSTARTEGY_DEF  = "standard";
#jod.permissions.owner: '00000-00000-00000'        # JODPERM_OWNER_DEF        = JOSPPerm.WildCards.USR_ANONYMOUS_ID.toString();


## Communication local

#jod.comm.local.enabled: 'false'                   # JODCOMM_LOCAL_ENABLED_DEF    = "true";
#jod.comm.local.discovery: 'Avahi'                 # JODCOMM_LOCAL_DISCOVERY_DEF  = "Auto";
#jod.comm.local.port: '1234'                       # JODCOMM_LOCAL_PORT_DEF       = "0";


## Communication cloud

#jod.comm.cloud.enabled: 'false'                   # JODCOMM_CLOUD_ENABLED_DEF    = "true";
